language: python

python:
  - "3.7"

install:
  - pip install black flake8 poetry
  - poetry update

before_script: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

script:
  - "make"
  - "make test"

notifications:
  email:
    on_success: never
    on_failure: always
